name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build ./parkingspace --file ./parkingspace/Dockerfile --tag cps2naveen-parking-backend:latest

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Push Docker Image to Docker Hub
    - name: Push Docker image to Docker Hub
      run: |
        docker push cps2naveen-parking-backend:latest
